### ISSUE TITLE
no response msg

### ISSUE THREAD

**Issue by jmery24** [ShowMeTheGita/whapp-futbot#20]
Hello
I tried to install the app to test and I can't get it to reply to my messages or I'm not understanding how it works.
I have performed npm I
web update
npm install whatsapp-web.js
node-index-dev.js

and i changed the phone number
But when I put the accepted commands for example !help , the bot does nothing.
The message reaches the console, but nothing else

Thanks

**Comment by ShowMeTheGita** [comment]
Hey @jmery24 thanks for taking interest in the repo, I never though it would gain any visibility.  
As it stands right now the bot is limiting responses to a specific group chat. If you run `node index-prod.js` after `npm install` then you'll be able to see on that index-prod.js file, line 4, the group id I was using to limit the responses to.  
If you want to the bot to respond to EVERY chat you receive, then you will have to remove the if condition located in 'whapp.js', lines 29 to 31:  
```
            if (message.from === this.#chat) {
                this.#client.sendMessage(message.from, this.#rsp.processMessage(message.body, message._data.notifyName), )
            }
```
Keep the contents inside the if, but remove the condition.  
Also the bot reads all messages received, but only responds to the ones I've hardcoded him to. On `classes.js` the function ` processMessage` is responsible for doing this, using a switch case to validate if the message received is a command or not. Only cases inside the function's switch case will be answered. For example, !help and !status would be commands it would respond to. You can obviously change this to your liking.  

Hope that helps :)

**Comment by ShowMeTheGita** [comment]
Also the number you used to scan the QR code when starting the application will be number the bot uses to send the replies with, meaning you need another phone number to test the application.  
As stated, removing the if condition will reply to ALL incoming chats that meet the criteria in the switch cases, but you can further limit the chats the bot responds to by adding your own list of approved chat or group ids.  
You can find the chat/group ids and a bunch more information about the sender by uncomentting line 26 of `whapp.js` and receiving any message at all.  
That console.log will be outputting a json with info about the sender such as whatsapp id (or group id if it's a group), name, number, URL to the whatsapp profile picture, message body, etc, amongst a bunch of other things you can use for your response back.

**Comment by ShowMeTheGita** [comment]
Another helpful tip - you can reuse this repo for the whatsapp bot replying functionalities, but I would advise on completely redoing the 'Responder' class in classes.js as it's very specific to what I was looking to achieve.  

If you want a fresh start, try adding something simple on the `run()` method of whapp.js and go from there. Here's what I started with:  

    run() {

        this.#client.on('message', (message) => {
            console.log(message)
            this.#client.sendMessage(message.from, 'hello world, this is a reply!')
        });


    }
